name: Release Templates

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        shell: bash
        run: |
          tar -czvf dart-${{ github.ref_name }}.tar.gz dart && mv dart-${{ github.ref_name }}.tar.gz artifacts/
          tar -czvf elixir-${{ github.ref_name }}.tar.gz elixir && mv elixir-${{ github.ref_name }}.tar.gz artifacts/
          tar -czvf go-${{ github.ref_name }}.tar.gz go && mv go-${{ github.ref_name }}.tar.gz artifacts/
          tar -czvf java-spring-${{ github.ref_name }}.tar.gz java-spring && mv java-spring-${{ github.ref_name }}.tar.gz artifacts/
          tar -czvf java-std-${{ github.ref_name }}.tar.gz java-std && mv java-std-${{ github.ref_name }}.tar.gz artifacts/
          tar -czvf nodejs-${{ github.ref_name }}.tar.gz nodejs && mv nodejs-${{ github.ref_name }}.tar.gz artifacts/
          tar -czvf python-${{ github.ref_name }}.tar.gz rust && mv python-${{ github.ref_name }}.tar.gz artifacts/
          tar -czvf rust-${{ github.ref_name }}.tar.gz rust && mv rust-${{ github.ref_name }}.tar.gz artifacts/

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}

      - name: Upload binaries to release
        if: always()
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/*.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: ${{ steps.changelog.outputs.changes }}

      - name: Cleanup
        shell: bash
        run: |
          rm -rf artifacts/dart-${{ github.ref_name }}.tar.gz 
          rm -rf artifacts/elixir-${{ github.ref_name }}.tar.gz 
          rm -rf artifacts/go-${{ github.ref_name }}.tar.gz 
          rm -rf artifacts/java-spring-${{ github.ref_name }}.tar.gz 
          rm -rf artifacts/java-std-${{ github.ref_name }}.tar.gz 
          rm -rf artifacts/nodejs-${{ github.ref_name }}.tar.gz 
          rm -rf artifacts/python-${{ github.ref_name }}.tar.gz 
          rm -rf artifacts/rust-${{ github.ref_name }}.tar.gz
