name: Release Templates

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Generate Tarballs
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      ImageOS: ubuntu20

    steps:
      - uses: actions/checkout@v3

      - name: Run Generate Tarballs
        run: |
          echo "TODO generate tarballs"
